[colors]
ansi = [
  "#0D0C0C",
  "#C4746E",
  "#8A9A7B",
  "#C4B28A",
  "#8BA4B0",
  "#A292A3",
  "#8EA4A2",
  "#C8C093",
]
background = "#181616"
brights = [
  "#A6A69C",
  "#E46876",
  "#87A987",
  "#E6C384",
  "#7FB4CA",
  "#938AA9",
  "#7AA89F",
  "#C5C9C5",
]
cursor_bg = "#C8C093"
cursor_border = "#C8C093"
cursor_fg = "#C8C093"
foreground = "#c5c9c5"
scrollbar_thumb = "#16161D"
selection_fg = "#C8C093"
selection_bg = "#2D4F67"
split = "#16161D"

[colors.indexed]
16 = "#B6927B"
17 = "#B98D7B"

[metadata]
aliases = []
author = "bivsk"
name = "Kanagawa Dragon"
